namespace Foundry.Models;

/// <summary>
/// Operator daily-run plan generated by the Foundry pipeline.
/// Persisted in the LiteDB <c>operator_daily_runs</c> collection, keyed by date.
/// </summary>
public sealed class DailyRunTemplate
{
    /// <summary>ISO date string for the day this plan applies to (e.g. "2024-11-15").</summary>
    public string DateKey { get; set; } = DateTime.Now.ToString("yyyy-MM-dd");

    /// <summary>High-level objective for the day.</summary>
    public string Objective { get; set; } = "No daily operator plan generated yet.";

    /// <summary>Morning work plan block (tasks to start the day).</summary>
    public string MorningPlan { get; set; } = string.Empty;

    /// <summary>Dedicated study block describing what to study and for how long.</summary>
    public string StudyBlock { get; set; } = string.Empty;

    /// <summary>Repository tasks block (PR reviews, commits, issues).</summary>
    public string RepoBlock { get; set; } = string.Empty;

    /// <summary>Mid-day checkpoint notes.</summary>
    public string MiddayCheckpoint { get; set; } = string.Empty;

    /// <summary>End-of-day review notes.</summary>
    public string EndOfDayReview { get; set; } = string.Empty;

    /// <summary>Tasks carried over from the previous day that are not yet complete.</summary>
    public List<string> CarryoverQueue { get; set; } = [];

    /// <summary>How the plan was generated (e.g. "ollama", "manual", "not generated").</summary>
    public string GenerationSource { get; set; } = "not generated";

    /// <summary>When the plan was generated.</summary>
    public DateTimeOffset GeneratedAt { get; set; } = DateTimeOffset.Now;

    /// <summary>Compact one-line display string for logs or the Discord bot.</summary>
    public string DisplaySummary =>
        $"{DateKey} | {GenerationSource} | {CarryoverQueue.Count} carryover items";
}
