namespace Foundry.Models;

/// <summary>
/// Result produced by the scikit-learn analytics engine (or its heuristic fallback).
/// Contains topic readiness scores, cluster assignments, adaptive schedule recommendations,
/// operator decision patterns, and optional Bayesian/forgetting-curve estimates.
/// </summary>
public sealed class MLAnalyticsResult
{
    /// <summary>Whether the ML engine ran successfully (false when falling back to heuristics).</summary>
    public bool Ok { get; init; }

    /// <summary>Which engine produced this result: "onnx", "python", or "heuristic".</summary>
    public string Engine { get; init; } = "heuristic";

    /// <summary>Topics with below-average accuracy that need additional study.</summary>
    public IReadOnlyList<MLTopicEntry> WeakTopics { get; init; } = Array.Empty<MLTopicEntry>();

    /// <summary>Topics where the operator has demonstrated strong accuracy.</summary>
    public IReadOnlyList<MLTopicEntry> StrongTopics { get; init; } = Array.Empty<MLTopicEntry>();

    /// <summary>Aggregate readiness score across all topics, in the range [0, 1].</summary>
    public double OverallReadiness { get; init; }

    /// <summary>
    /// Topic clusters produced by the scikit-learn clustering step.
    /// Labels flow into the PyTorch embedding stage as part of the EngineHandoff contract.
    /// </summary>
    public IReadOnlyList<MLTopicCluster> TopicClusters { get; init; } = Array.Empty<MLTopicCluster>();

    /// <summary>Prioritized study schedule generated by the adaptive scheduling algorithm.</summary>
    public IReadOnlyList<MLScheduleItem> AdaptiveSchedule { get; init; } = Array.Empty<MLScheduleItem>();

    /// <summary>Aggregate approve/reject/defer decision pattern for the operator.</summary>
    public MLOperatorPattern OperatorPattern { get; init; } = new();

    /// <summary>Per-topic readiness breakdown with confidence intervals and trend data.</summary>
    public IReadOnlyList<MLReadinessEntry> ReadinessBreakdown { get; init; } = Array.Empty<MLReadinessEntry>();

    /// <summary>Error message from the scikit-learn engine, if any.</summary>
    public string? SklearnError { get; init; }

    /// <summary>Per-topic forgetting-curve models (null when not enough data or engine unavailable).</summary>
    public IReadOnlyDictionary<string, MLForgettingCurve>? ForgettingCurves { get; init; }

    /// <summary>Per-topic Bayesian accuracy estimates with 90 % credible intervals.</summary>
    public IReadOnlyDictionary<string, MLBayesianEstimate>? BayesianEstimates { get; init; }

    /// <summary>Per-topic plateau detection results from the scikit-learn engine.</summary>
    public IReadOnlyDictionary<string, MLPlateauStatus>? PlateauStatus { get; init; }
}

/// <summary>Accuracy statistics for a single study topic.</summary>
public sealed class MLTopicEntry
{
    /// <summary>Name of the study topic.</summary>
    public string Topic { get; init; } = string.Empty;

    /// <summary>Fraction of questions answered correctly, in the range [0, 1].</summary>
    public double Accuracy { get; init; }

    /// <summary>Total number of questions attempted for this topic.</summary>
    public int TotalQuestions { get; init; }

    /// <summary>Number of questions answered correctly.</summary>
    public int CorrectCount { get; init; }
}

/// <summary>
/// A cluster of related study topics produced by the scikit-learn clustering step.
/// Cluster labels are passed to the PyTorch engine as part of the EngineHandoff contract.
/// </summary>
public sealed class MLTopicCluster
{
    /// <summary>Zero-based cluster identifier assigned by the clustering algorithm.</summary>
    public int ClusterId { get; init; }

    /// <summary>Topics grouped into this cluster.</summary>
    public IReadOnlyList<string> Topics { get; init; } = Array.Empty<string>();

    /// <summary>Mean accuracy across all topics in the cluster.</summary>
    public double AverageAccuracy { get; init; }

    /// <summary>Mean memory stability (days) across topics in the cluster, when available.</summary>
    public double? AverageStability { get; init; }

    /// <summary>Human-readable label for the cluster (e.g. "weak", "moderate", "strong").</summary>
    public string Label { get; init; } = string.Empty;
}

/// <summary>A single entry in the adaptive study schedule.</summary>
public sealed class MLScheduleItem
{
    /// <summary>Name of the study topic.</summary>
    public string Topic { get; init; } = string.Empty;

    /// <summary>Scheduling priority (lower is higher priority).</summary>
    public int Priority { get; init; }

    /// <summary>Recommended session type (e.g. "practice", "review", "challenge").</summary>
    public string RecommendedSessionType { get; init; } = "practice";

    /// <summary>Suggested number of days until the next study session.</summary>
    public int IntervalDays { get; init; }

    /// <summary>Human-readable explanation of why this topic was scheduled.</summary>
    public string Reason { get; init; } = string.Empty;

    /// <summary>Average gap in days between past study sessions for this topic.</summary>
    public double? AverageStudyGapDays { get; init; }

    /// <summary>Whether the interval was derived from the forgetting-curve model.</summary>
    public bool? ForgettingCurveInterval { get; init; }
}

/// <summary>Aggregate statistics about the operator's approve/reject/defer decision behavior.</summary>
public sealed class MLOperatorPattern
{
    /// <summary>Fraction of decisions that were approvals, in the range [0, 1].</summary>
    public double ApproveRate { get; init; }

    /// <summary>Fraction of decisions that were rejections, in the range [0, 1].</summary>
    public double RejectRate { get; init; }

    /// <summary>Fraction of decisions that were deferrals, in the range [0, 1].</summary>
    public double DeferRate { get; init; }

    /// <summary>Total number of operator decisions in the analysis window.</summary>
    public int TotalDecisions { get; init; }

    /// <summary>Named pattern label (e.g. "balanced", "approve-heavy", "defer-heavy").</summary>
    public string Pattern { get; init; } = "balanced";
}

/// <summary>Per-topic readiness entry with confidence, trend, and Bayesian estimates.</summary>
public sealed class MLReadinessEntry
{
    /// <summary>Name of the study topic.</summary>
    public string Topic { get; init; } = string.Empty;

    /// <summary>Composite readiness score in the range [0, 1].</summary>
    public double Readiness { get; init; }

    /// <summary>Model confidence in the readiness estimate, in the range [0, 1].</summary>
    public double Confidence { get; init; }

    /// <summary>Recent accuracy trend (positive = improving, negative = declining).</summary>
    public double? Trend { get; init; }

    /// <summary>Whether accuracy has been trending upward over recent sessions.</summary>
    public bool? Improving { get; init; }

    /// <summary>Bayesian posterior mean accuracy estimate.</summary>
    public double? BayesianMean { get; init; }

    /// <summary>Lower bound of the 90 % Bayesian credible interval.</summary>
    public double? CredibleIntervalLower { get; init; }

    /// <summary>Upper bound of the 90 % Bayesian credible interval.</summary>
    public double? CredibleIntervalUpper { get; init; }

    /// <summary>Estimated memory stability in days (from the forgetting-curve model).</summary>
    public double? StabilityDays { get; init; }

    /// <summary>Whether accuracy has plateaued (no meaningful improvement over recent sessions).</summary>
    public bool? Plateaued { get; init; }

    /// <summary>Recommended action when a plateau is detected.</summary>
    public string? PlateauRecommendation { get; init; }
}

/// <summary>
/// Forgetting-curve model for a single topic, estimating predicted retention at future time points.
/// </summary>
public sealed class MLForgettingCurve
{
    /// <summary>Estimated memory stability in days (how long before retention drops to ~37 %).</summary>
    public double StabilityDays { get; init; }

    /// <summary>
    /// Predicted retention at future review intervals.
    /// Keys are human-readable time labels (e.g. "1d", "7d"), values are retention fractions in [0, 1].
    /// </summary>
    public IReadOnlyDictionary<string, double>? PredictedRetention { get; init; }
}

/// <summary>Bayesian posterior accuracy estimate with a 90 % credible interval.</summary>
public sealed class MLBayesianEstimate
{
    /// <summary>Posterior mean accuracy.</summary>
    public double Mean { get; init; }

    /// <summary>Lower bound of the 90 % credible interval.</summary>
    public double Lower90 { get; init; }

    /// <summary>Upper bound of the 90 % credible interval.</summary>
    public double Upper90 { get; init; }

    /// <summary>Number of posterior samples used to compute the estimate.</summary>
    public int Samples { get; init; }
}

/// <summary>Plateau detection result for a single topic.</summary>
public sealed class MLPlateauStatus
{
    /// <summary>Whether accuracy has plateaued (no meaningful improvement detected).</summary>
    public bool Plateaued { get; init; }

    /// <summary>The accuracy level at which the plateau was detected.</summary>
    public double? Accuracy { get; init; }

    /// <summary>Whether accuracy is actively regressing rather than simply flat.</summary>
    public bool? Regressing { get; init; }

    /// <summary>Explanation of why a plateau or regression was detected.</summary>
    public string? Reason { get; init; }

    /// <summary>Suggested action to break through the plateau or reverse the regression.</summary>
    public string? Recommendation { get; init; }
}
