namespace Foundry.Models;

/// <summary>
/// Versioned ML artifact bundle consumed by the Suite project.
/// Generated by the Python <c>ml_suite_artifacts.py</c> script and exported to the state directory.
/// </summary>
public sealed class SuiteMLArtifactBundle
{
    /// <summary>Whether the artifact bundle was generated successfully.</summary>
    public bool Ok { get; init; }

    /// <summary>ISO 8601 timestamp when the bundle was generated.</summary>
    public string GeneratedAt { get; init; } = string.Empty;

    /// <summary>Individual typed artifacts contained in the bundle.</summary>
    public IReadOnlyList<SuiteMLArtifact> Artifacts { get; init; } = Array.Empty<SuiteMLArtifact>();
}

/// <summary>
/// A single versioned ML artifact within a <see cref="SuiteMLArtifactBundle"/>.
/// </summary>
public sealed class SuiteMLArtifact
{
    /// <summary>Type identifier for the artifact (e.g. "analytics", "embeddings", "forecast").</summary>
    public string ArtifactType { get; init; } = string.Empty;

    /// <summary>Semantic version of the artifact schema.</summary>
    public string Version { get; init; } = "1.0.0";

    /// <summary>ISO 8601 timestamp when this artifact was generated.</summary>
    public string GeneratedAt { get; init; } = string.Empty;

    /// <summary>Identifier of the pipeline that produced this artifact.</summary>
    public string Source { get; init; } = "office-ml-pipeline";

    /// <summary>Whether the consuming project must manually review this artifact before use.</summary>
    public bool ReviewRequired { get; init; } = true;

    /// <summary>Artifact payload; the shape depends on <see cref="ArtifactType"/>.</summary>
    public object? Data { get; init; }
}
